- name: upgrade debian os
  apt:
    update_cache: yes
    cache_valid_time: '{{ apt_cache_valid_time }}'

- name: update all packages
  apt:
    name: '*'
    state: latest
    
- name: apt dist upgrade
  apt:
    upgrade: dist