---
- hosts: all
  become: true
  vars:
    the_user: ansible

  tasks:
    - name: create user
      user:
        name: "{{ the_user }}"
        group: ansible
        shell: /bin/bash
        state: present
        create_home: true

    - name: create SSH key
      user:
        name: "{{ the_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_type: rsa
        ssh_key_file: .ssh/id_rsa

    - name: set password
      user:
        name: "{{ the_user }}"
        password: "password"
        password_expire_min: 14
        password_expire_max: 1000
