---
- name: Install database
  become: true
  apt:
    name:
     - mariadb-server-10.3
     - mariadb-server
     - python3-pip
    state: latest
    update_cache: yes
    cache_valid_time: 3600    

- name: Install pymysql
  shell: python3 -m pip install pymysql

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Remove mysql test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove all ananymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  notify: restart_mysql